spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: member-service
        uri: lb://MEMBER-SERVICE
        predicates:
        - Path=/member-service/api/v1/**
        filters:
        - RewritePath=/member-service/api/v1/(?<path>.*), /members/v1/$\{path}
      - id: contract-service
        uri: lb://CONTRACT-SERVICE
        predicates:
        - Path=/contract-service/api/v1/**
        filters:
        - RewritePath=/contract-service/api/v1/(?<path>.*), /contracts/v1/$\{path}
      - id: document-service
        uri: lb://DOCUMENT-SERVICE
        predicates:
        - Path=/document-service/api/v1/**
        filters:
        - RewritePath=/document-service/api/v1/(?<path>.*), /documents/v1/$\{path}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    preferIpAddress: true
