spring:
  application:
    name: member-service
  r2dbc:
    url: r2dbc:postgresql://192.168.1.100:5432/HFG?schema=public
    username: postgres
    password: postgres123
  profiles:
    active:
    - dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    preferIpAddress: true